wrapping in function

diff --git a/dev_install b/dev_install
--- a/dev_install
+++ b/dev_install
@@ -1,63 +1,67 @@
 #!/bin/bash
-set -e
-exec > >(tee $0.log) 2>&1
 
-username=$(whoami)
+blast_off(){
+  set -e
+  exec > >(tee $0.log) 2>&1
 
-# check for Apple XCode
-xcode-select -v
-if [ $? -ne 0 ]; then  # need to fix this check or remove
-  echo "Apple Xcode command line tools not installed!!!"
-  echo "Run 'xcode-select --install'"
-  echo "Once complete, restart your computer and re-run this script."
-  exit 1
-fi
+  username=$(whoami)
 
-if [[ $( basename $SHELL ) = "zsh" ]]; then
-  echo "-- Your shell is already set to ZSH!"
-else
-  echo "--- Making /bin/zsh the default shell ---"
-  read -s -p "Password: " password
-  echo
-  echo $password | sudo -S chsh -s /bin/zsh $username
-fi
+  # check for Apple XCode
+  xcode-select -v
+  if [ $? -ne 0 ]; then  # need to fix this check or remove
+    echo "Apple Xcode command line tools not installed!!!"
+    echo "Run 'xcode-select --install'"
+    echo "Once complete, restart your computer and re-run this script."
+    exit 1
+  fi
 
-if which brew >/dev/null; then
-  echo "-- Homebrew Already Installed!"
-else
-  echo "-- Installing Homebrew ..."
-  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/install/master/install)"
-fi
+  if [[ $( basename $SHELL ) = "zsh" ]]; then
+    echo "-- Your shell is already set to ZSH!"
+  else
+    echo "--- Making /bin/zsh the default shell ---"
+    read -s -p "Password: " password
+    echo
+    echo $password | sudo -S chsh -s /bin/zsh $username
+  fi
+
+  if which brew >/dev/null; then
+    echo "-- Homebrew Already Installed!"
+  else
+    echo "-- Installing Homebrew ..."
+    ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/install/master/install)"
+  fi
 
 
-echo "--- Installing Apps ---"
-brew tap Homebrew/bundle
-brew bundle || echo "Apps installed! Note any errors." 
+  echo "--- Installing Apps ---"
+  brew tap Homebrew/bundle
+  brew bundle || echo "Apps installed! Note any errors." 
 
-echo "--- Install Oh My ZSH ---"
-curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
+  echo "--- Install Oh My ZSH ---"
+  curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
 
-echo "--- Update ~/.zshrc and ~/.bash_profile ---"
-cat environment >> ~/.zshrc
-cat environment >> ~/.bash_profile
-source ~/.bash_profile
+  echo "--- Update ~/.zshrc and ~/.bash_profile ---"
+  cat environment >> ~/.zshrc
+  cat environment >> ~/.bash_profile
+  source ~/.bash_profile
 
-echo "--- Install Rubies ---"
-RubyVersions=( '2.2.3' );
-for version in "${RubyVersions[@]}"; do
-  ruby-install ruby $version
-done
+  echo "--- Install Rubies ---"
+  RubyVersions=( '2.2.3' );
+  for version in "${RubyVersions[@]}"; do
+    ruby-install ruby $version
+  done
 
-default_ruby=${RubyVersions[0]}
-echo "--- Set the Default Ruby Version to $default_ruby ---"
-chruby $default_ruby
-echo $default_ruby > ~/.ruby-version
+  default_ruby=${RubyVersions[0]}
+  echo "--- Set the Default Ruby Version to $default_ruby ---"
+  chruby $default_ruby
+  echo $default_ruby > ~/.ruby-version
 
-echo "--- Install Gems ---"
-cp .gemrc ~/.gemrc
-gem install bundler
-bundle install
+  echo "--- Install Gems ---"
+  cp .gemrc ~/.gemrc
+  gem install bundler
+  bundle install
 
-echo "--- Developer Tools Install Script Complete! ---"
-echo "Restart your terminal to load the new changes."
-echo "Then, run './dev_check' to verify the installation."
+  echo "--- Developer Tools Install Script Complete! ---"
+  echo "Restart your terminal to load the new changes."
+  echo "Then, run './dev_check' to verify the installation."
+}
+blast_off()
